theme: jekyll-theme-minimal
title: Octocat's homepage
description: Bookmark this to keep an eye on my project updates!
layout: page
title: "PAGE-TITLE"
permalink: https://jagpreet25700.github.io/Jagpreet25700/
